# Generated by Django 3.1.7 on 2022-05-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='isbn')),
                ('image', models.CharField(max_length=5000, verbose_name='image')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('description', models.CharField(max_length=2000, verbose_name='image')),
                ('publisher', models.CharField(max_length=500, verbose_name='offers')),
                ('authors', models.CharField(max_length=1000, verbose_name='description')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='intial date')),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'books',
            },
        ),
    ]
