# Generated by Django 3.1.7 on 2022-05-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220526_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='description'),
        ),
    ]
