# Generated by Django 3.1.7 on 2022-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20220526_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='publisher'),
        ),
    ]
