# Generated by Django 3.1.7 on 2022-05-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20220526_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, verbose_name='isbn'),
        ),
    ]
