# Generated by Django 3.1.7 on 2022-05-30 18:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20220526_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriateness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='appropriateness')),
                ('efectiveness', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='efectiveness')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='value')),
                ('visual_aids', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='visual aids')),
                ('overall', models.IntegerField(validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='overall')),
                ('recommend', models.BooleanField(verbose_name='recommend')),
                ('instructor_manual_provided', models.BooleanField(verbose_name='instructor manual provided')),
                ('teaching_slides_provided', models.BooleanField(verbose_name='teaching_slides_provided')),
                ('question_bank_provided', models.BooleanField(verbose_name='question_bank_provided')),
                ('digital_resource_provided', models.BooleanField(verbose_name='digital_resource_provided')),
                ('assigments_provided', models.BooleanField(verbose_name='assigments_provided')),
                ('instructor_manual_used', models.BooleanField(verbose_name='instructor manual used')),
                ('teaching_slides_used', models.BooleanField(verbose_name='teaching_slides_used')),
                ('question_bank_used', models.BooleanField(verbose_name='question_bank_used')),
                ('digital_resource_used', models.BooleanField(verbose_name='digital_resource_used')),
                ('assigments_used', models.BooleanField(verbose_name='assigments_used')),
                ('use_again', models.BooleanField(verbose_name='use again')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='comments')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books', verbose_name='Book')),
            ],
            options={
                'verbose_name': 'book rating',
                'verbose_name_plural': 'book ratings',
            },
        ),
    ]
