# Generated by Django 3.1.7 on 2022-05-31 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220511_2055'),
        ('books', '0007_booksratings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksratings',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.studyarea', verbose_name='subject'),
        ),
    ]
