# Generated by Django 3.1.7 on 2022-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20220531_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='description'),
        ),
    ]
