version: '3'

volumes:
  local_db_data: {}


networks:
  knowquest_network:
    name: knowquest
    driver: bridge
    ipam:
      driver: default

services:
  app:
    container_name: django-knowquest
    build:
      context: .
      dockerfile: Django-Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    networks:
      knowquest_network:
        aliases:
          - app
  
  db:
    container_name: postgres-knowquest
    image: postgres:12.3
    environment:
      - POSTGRES_DB=knowquest
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin12345
    volumes:
      - local_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      knowquest_network:
        aliases:
          - db
  

  react:
    container_name: react-knowquest
    build:
      context: .
      dockerfile: React-Dockerfile
    volumes:
      - './front:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      knowquest_network:
        aliases:
          - react