# Generated by Django 3.1.7 on 2022-05-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220510_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=250, unique=True, verbose_name='School')),
            ],
            options={
                'verbose_name': 'domain',
                'verbose_name_plural': 'domainss',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Set to true when the user have verified its email address.', verbose_name='verified'),
        ),
    ]
