# Generated by Django 3.1.7 on 2022-07-18 17:27

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_superuser(apps, schema_editor):
    User = apps.get_model("users", "User")
    UserRole = apps.get_model("users", "UserRole")
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.is_verified = True
    superuser.role = UserRole.objects.get(role='admin')
    superuser.username = 'admin'
    superuser.email = 'admin@knowquest.com'
    superuser.password =  make_password('admin12345')
    superuser.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220511_2055'),
    ]

    operations = [
         migrations.RunPython(create_superuser)
    ]
