# Generated by Django 3.1.7 on 2022-07-25 02:47

from django.db import migrations


def create_default_study_areas(apps, schema_editor):
    study_area = apps.get_model("users", "StudyArea")

    study_area.objects.create(name="Arts and Animation")
    study_area.objects.create(name="Aviation")
    study_area.objects.create(name="Business and Economics")
    study_area.objects.create(name="Community Services")
    study_area.objects.create(name="Environment and Horticulture")
    study_area.objects.create(name="Fashion and Aesthetics")
    study_area.objects.create(name="Health Services")
    study_area.objects.create(name="Information and Communication Technology")
    study_area.objects.create(name="Hospitality, Tourism, Food and Sport")
    study_area.objects.create(name="Law, Public Administration and Public Safety")
    study_area.objects.create(name="Liberal Arts and Sciences")
    study_area.objects.create(name="Manufacturing and Trades")
    study_area.objects.create(name="Media and Communication")
    study_area.objects.create(name="Nursing and Personal Support Working")
    study_area.objects.create(name="Recreation and Wellness")
    study_area.objects.create(name="Science, Engineering and Construction")
    study_area.objects.create(name="Psychology")
    study_area.objects.create(name="Geography")
    study_area.objects.create(name="Languages")
    study_area.objects.create(name="Sociology")
    study_area.objects.create(name="History")
    study_area.objects.create(name="Political Science")
    study_area.objects.create(name="Computer Science")
    study_area.objects.create(name="Education")
    study_area.objects.create(name="Medicine")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_createsuperuser'),
    ]

    operations = [
        migrations.RunPython(create_default_study_areas),
    ]
