# Generated by Django 3.1.7 on 2022-07-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20220713_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='title')),
            ],
            options={
                'verbose_name': 'media type',
                'verbose_name_plural': 'media types',
            },
        ),
        migrations.RemoveField(
            model_name='resourcesratings',
            name='resource_type',
        ),
        migrations.AddField(
            model_name='resourcesratings',
            name='created',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='resources',
            name='media_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.mediatype', verbose_name='media type'),
        ),
    ]
