# Generated by Django 3.1.7 on 2022-07-25 02:54

from django.db import migrations

def create_default_media_types(apps, schema_editor):
    resources = apps.get_model("resources", "MediaType")

    resources.objects.create(name="PowerPoint (or other) Slides")
    resources.objects.create(name="YouTube")
    resources.objects.create(name="Khan Academy")
    resources.objects.create(name="Linkedln Learning")
    resources.objects.create(name="Open Education Resources")
    resources.objects.create(name="Website")
    resources.objects.create(name="Audio")
    resources.objects.create(name="Others")


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_auto_20220713_1820'),
    ]

    operations = [
        migrations.RunPython(create_default_media_types),
    ]
