# Generated by Django 3.1.7 on 2022-05-31 17:04

from django.db import migrations

def create_default_levels(apps, schema_editor):
    level = apps.get_model("ratings_catalogs", "Level")

    level.objects.create(name="1st Year University")
    level.objects.create(name="2nd Year University")
    level.objects.create(name="3rd Year University")
    level.objects.create(name="4th Year University")
    level.objects.create(name="1st Year Graduate")
    level.objects.create(name="2nd Year Graduate")
    level.objects.create(name="3rd Year Graduate")
    level.objects.create(name="4th Year Graduate")
    level.objects.create(name="1st Year Doctoral")
    level.objects.create(name="2nd Year Doctoral")
    level.objects.create(name="3rd Year Doctoral")
    level.objects.create(name="Post Doctoral")
    level.objects.create(name="1st Year College")
    level.objects.create(name="2nd Year College")
    level.objects.create(name="3rd Year College")
    level.objects.create(name="4th Year College")
    level.objects.create(name="Other")

def create_default_semesters(apps, schema_editor):
    semester = apps.get_model("ratings_catalogs", "Semester")

    semester.objects.create(name="FALL")
    semester.objects.create(name="SUMMER")
    semester.objects.create(name="SPRING")
    semester.objects.create(name="WINTER")
    semester.objects.create(name="FALL-WINTER")
    semester.objects.create(name="SPRING-SUMMER")


def create_default_costs(apps, schema_editor):
    cost = apps.get_model("ratings_catalogs", "Cost")

    cost.objects.create(name="Cost Not Available")
    cost.objects.create(name="$1-$9.99")
    cost.objects.create(name="$10-$29.99")
    cost.objects.create(name="$30-$49.99")
    cost.objects.create(name="$50-$99.99")
    cost.objects.create(name="$100-$149")
    cost.objects.create(name="$150-$199")
    cost.objects.create(name="$200+")
    cost.objects.create(name="Free")


class Migration(migrations.Migration):

    dependencies = [
        ('ratings_catalogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_levels),
        migrations.RunPython(create_default_semesters),
        migrations.RunPython(create_default_costs),
    ]
