# Generated by Django 3.1.7 on 2022-05-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='final_limited_time',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='initial_limited_time',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='contests',
            name='offers',
        ),
        migrations.AlterField(
            model_name='contests',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='logo',
            field=models.ImageField(default='default.jpg', max_length=1000, upload_to='contests/logo/%Y/%m/%d/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='contests',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='name'),
        ),
    ]
